Mobile skeleton
prince-rutagengwa/mobile-skeleto pull request #1
Opened 2022-03-18 13:20 UTC by prince-rutagengwa

in this project I:
- Added HTML to the Figma template of my choice,
- Added styling to that HTML,
- Added a clear README file that contains all the necessary info about my work.

2022-03-18 15:23 UTC, zainsadaqat requested changes
# Hey @prince-rutagengwa 😃 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
  ✅  Descriptive Pull Request
  ✅ Correct use of GitHub Flow
  ✅ No linter errors

## Required Changes ♻️

**Your Design**

- [ ] Please add the background image as per Figma Design
- [ ] Please use the font face as per requirement

<img width="384" alt="Screen Shot 2022-03-18 at 7 48 45 PM" src="https://user-images.githubusercontent.com/83048208/159025401-9ebbc952-24ab-473a-bff5-62ef9a08c1b1.png">

**Figma Design**

<img width="359" alt="Screen Shot 2022-03-18 at 7 50 12 PM" src="https://user-images.githubusercontent.com/83048208/159025653-acdfb604-a26c-4486-9db0-444f88a286fc.png">




_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 15:23 UTC, zainsadaqat commented on README.md
> +# mobile-skeleton
Please add project name, Kindly replace `mobile-skeleton` with `<your-project-name>`

2022-03-18 15:23 UTC, zainsadaqat commented on index.html
> +    <title>Document</title>
Kindly add your project name here in the title

2022-03-18 15:23 UTC, zainsadaqat commented on index.html
> +</header>
### Please perform the following:

- [ ] Move this `<header>` section inside of `<body>` tag
- [ ] Wrap logo with `<a>` tag
- [ ] Use `<ul>` `<li>` tags instead of div to make it more SEO friendly

2022-03-18 15:23 UTC, zainsadaqat commented on index.html
> +     <p><h3 class="basic-info">I am student at microverse</h3></p>
For paragraphs kindly use only `<p>` tag. Please remove the `<h3>` tag.

2022-03-18 15:23 UTC, zainsadaqat commented on index.html
> +    </nav>
`<nav>` is used for the navigation which is mostly in the menu bar or side bar. Please replace `<nav>` with `<ul>` `<li>` tags.

2022-03-18 15:23 UTC, zainsadaqat commented on style.css
> +}
[Optional]
It's not recommended to style and use flex for the whole body tag. You may style divs, sections separately.

2022-03-18 15:23 UTC, zainsadaqat commented on index.html
> +        <nav class="logo">Prince Rutagengwa</nav>
Kindly wrap the logo with `<a>` tag and use a semantic HTML tag for the logo.

2022-03-18 15:23 UTC, zainsadaqat commented on index.html
> +            <div class="bar3"></div>
Please replace `<div>` with `<ul>` `<li>` tags to make more SEO friendly.

2022-03-19 00:46 UTC, smunozmo requested changes
Hi @prince-rutagengwa, 👋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 👏 

- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

<img src="https://media1.giphy.com/media/z5cNqbFbMTDA4/giphy.gif"/>


Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 00:46 UTC, smunozmo commented on style.css
> +  background-position: 88% 99%;*/
- [OPTIONAL] Remove any unused code, this will make your code cleaner.

2022-03-19 00:46 UTC, smunozmo commented on index.html
> +        <a href="#" class="logo"> Prince Rutagengwa</a>
- [ ] You did a great job, your project is almost ready, please fix your logo top margin which is still looking different from the template, just add some space from the top:

Template:
![Captura de pantalla 2022-03-18 a la(s) 7 42 11 p  m](https://user-images.githubusercontent.com/83717285/159100029-40b248d5-18c4-49fd-8da1-5b6667233429.png)

Your design:
![Captura de pantalla 2022-03-18 a la(s) 7 44 41 p  m](https://user-images.githubusercontent.com/83717285/159100084-ef4f7ecb-f1f9-470c-8055-a6a0c7ae7652.png)

2022-03-19 09:57 UTC, Mre55 approved these changes
**Hi @prince-rutagengwa,**

# Status: APPROVED 🎉 🎊 

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚀: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 10:00 UTC, merged